# File path and dataset name
path:       '/Volumes/FN_2187/ncep2/'
short_name: 'NCEP_NCAR_DAILY'

# Input file possibilities:
# n_vars x n_years
# single var/file, single year/file - n_vars * n_years files
single_var_file:    True    # Variables are in multiple files (if True)
single_year_file:   True    # Years are in multiple files (if True)
file_paths:
            uwnd:   'uwnd.{year:04d}.nc'
            vwnd:   'vwnd.{year:04d}.nc'
            tair:   'air.{year:04d}.nc'
            omega:  'omega.{year:04d}.nc'
            ipv:    'ipv.{year:04d}.nc'
            psi:    'psi.{year:04d}.nc'
            tpause: 'tpause.{year:04d}.nc'

lon:    'lon'   # Name within netCDF file of 'longitude' variable
lat:    'lat'   # Name within netCDF file of 'latitude' variable
lev:    'level' # Name within netCDF file of 'level' variable
time:   'time'  # Name within netCDF file of 'time' variable
ztype:  'pres'  # Type of levels (pressure, potential temperature, etc.)
pfac:   100.0   # Multiply pressure by this to get units of Pascals

# Variable names for u/v wind, air temperature and pv
uwnd:   'uwnd'
vwnd:   'vwnd'
tair:   'air'
omega:  'omega'
ipv:    'ipv'
