path: '/scratch/pm366/Data/ERA_INT_1979-2016/daily/'
wpath: '/scratch/pm366/Data/ERA_INT_1979-2016/daily/'

short_name: 'ERAI_PRES'

# Input file possibilities:
# n_vars x all_years

# IPV and Tropopause can be separate files since they _could_ be created outside the input
# file, so they have their own keys in `file_paths`, but can point to same as 'all'

# single var/file, multipule years/file :: n_vars files
single_var_file: True
single_year_file: False
file_paths:
    uwnd: 'u_19790101-20151231_dm_subset_lev.nc'
    vwnd: 'v_19790101-20151231_dm_subset_lev.nc'
    all: 'v_19790101-20151231_dm_subset_lev.nc'

lon: 'longitude'      # Name within netCDF file of 'longitude' variable
lat: 'latitude'      # Name within netCDF file of 'latitude' variable
lev: 'level'    # Name within netCDF file of 'level' variable
time: 'time'    # Name within netCDF file of 'time' variable
ztype: 'pres'   # Type of levels (pressure, potential temperature, etc.)
pfac: 1.0       # Multiply pressure by this to get units of Pascals

# Variable names for u/v wind, air temperature and pv
uwnd: 'u'
vwnd: 'v'

