path: '/scratch/pm366/Data/ERA_INT_1979-2016/monthly/'
wpath: '/scratch/mk450/Data/ERA_INT/monthly/'
short_name: 'ERAI_PRES'

# Input file possibilities:
# n_vars x all_years

# IPV and Tropopause can be separate files since they _could_ be created outside the input
# file, so they have their own keys in `file_paths`, but can point to same as 'all'

# single var/file, multipule years/file :: n_vars files
single_var_file: True
single_year_file: False
file_paths:
    uwnd: 'ERA-INT_197901_201612_u.nc'
    vwnd: 'ERA-INT_197901_201612_v.nc'
    tair: 'ERA-INT_197901_201612_t.nc'
    ipv: 'ERA-INT_197901_201612_ipv.nc'
    tpause: 'ERA-INT_197901_201612_tpause.nc'

lon: 'lon'      # Name within netCDF file of 'longitude' variable
lat: 'lat'      # Name within netCDF file of 'latitude' variable
lev: 'lev'    # Name within netCDF file of 'level' variable
time: 'time'    # Name within netCDF file of 'time' variable
ztype: 'pres'   # Type of levels (pressure, potential temperature, etc.)
pfac: 1.0     # Multiply pressure by this to get units of Pascals

# Variable names for u/v wind, air temperature and pv
tair: 'var130'
uwnd: 'var131'
vwnd: 'var132'
ipv: 'ipv'
