---
data_cfg: '{}/data_config_erai_monthly_gv.yml'
freq: 'mon'
zonal_opt: 'mean'
method: 'STJPV'
log_file: 'stj_find_erai_pres_mon_{}.log'
pv_value: 2.0
fit_deg: 8
min_lat: 10.0
update_pv: false
update_psi: false
year_s: 1979
year_e: 2016
poly: 'cheby'
